// packages/journey-engine/src/types.ts
// Pure data types — no I/O, no framework deps. See docs/ARCHITECTURE.md.

export interface StationNode {
  id: number;
  code: string;
  name: string;
  city: string;
  lat: number;
  lng: number;
}

/** One scheduled train segment between two consecutive stops on a train's route. */
export interface JourneyLeg {
  trainNumber: string;
  trainName: string;
  fromStationCode: string;
  toStationCode: string;
  departure: string; // ISO datetime, resolved to a specific calendar date
  arrival: string;   // ISO datetime
  durationMinutes: number;
  classCode: string;
  fareEstimate: number;
  /** General-quota advance reservation opening date (ISO), departure minus
   * IRCTC's current 60-day ARP (changed from 120 days in Nov 2024) — see
   * PRD note on this. Informational only: real ARP has exceptions this
   * doesn't model (short-distance trains ~15-30 days, FTQ 365 days), so
   * UI copy must hedge as "general quota, typically" not an absolute. */
  bookingOpensDate: string;
}

export type ConnectionRisk = 'green' | 'yellow' | 'red';

export interface ConnectionBuffer {
  atStationCode: string;
  minutes: number;
  risk: ConnectionRisk;
  reason: string;
}

export type BookingViability = 'high' | 'medium' | 'low' | 'unknown';

export interface Journey {
  legs: JourneyLeg[];
  totalFareEstimate: number;
  totalDurationMinutes: number;
  transferCount: number;
  connectionBuffers: ConnectionBuffer[];
  departureTime: string;
  arrivalTime: string;
  journeyQualityScore: number; // 0-100
  bookingViability: BookingViability;
  whyThisRoute: string[];
  cautions: string[];
  /** Set when this journey used a nearby station instead of the exact
   * one requested (see docs/PRD.md "never silently substituted") — the
   * *ExtraTravelMinutes fields are the real last-mile cost the user
   * needs to see alongside it, never hidden. */
  isOriginExpansion?: boolean;
  isDestinationExpansion?: boolean;
  originExtraTravelMinutes?: number;
  destExtraTravelMinutes?: number;
}

/** A single time-stamped directed edge in the graph, generated by
 * resolving a train's weekly schedule against one calendar date. */
export interface TemporalEdge {
  trainNumber: string;
  trainName: string;
  fromStationCode: string;
  toStationCode: string;
  departure: Date;
  arrival: Date;
  classCode: string;
  fareEstimate: number;
}

export interface SearchQuery {
  originStationCode: string;
  destinationStationCode: string;
  dateFrom: string; // 'YYYY-MM-DD'
  dateTo: string;
  budgetMax?: number;
  classes: string[];
  maxTransfers: number; // default handled by caller
  passengers: number;
}

export interface SearchConstraints {
  budgetMax?: number;
  classes: string[];
  maxTransfers: number;
  maxLegDurationMinutes?: number;
  minConnectionBufferMinutes: number; // below this => 'red', reject
  tightConnectionBufferMinutes: number; // below this (and above min) => 'yellow'
}

export const DEFAULT_CONSTRAINTS: Pick<
  SearchConstraints,
  'minConnectionBufferMinutes' | 'tightConnectionBufferMinutes'
> = {
  minConnectionBufferMinutes: 30,
  tightConnectionBufferMinutes: 90,
};
